// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Z​h​o​u​ ​H​u​a​`​s​ ​B​l​o​g
	 */
	title: string
	articleDetail: {
		/**
		 * R​e​a​d​ ​o​t​h​e​r​ ​a​r​t​i​c​l​e​s
		 */
		readOtherArticles: string
	}
}

export type TranslationFunctions = {
	/**
	 * Zhou Hua`s Blog
	 */
	title: () => LocalizedString
	articleDetail: {
		/**
		 * Read other articles
		 */
		readOtherArticles: () => LocalizedString
	}
}

export type Formatters = {}
